---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scale.madrid.operator.com
  resources:
  - scaledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.madrid.operator.com
  resources:
  - scaledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - scale.madrid.operator.com
  resources:
  - scaledeployments/status
  verbs:
  - get
  - patch
  - update
