# permissions for end users to edit scaledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lab-k8s-operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: scaledeployment-editor-role
rules:
- apiGroups:
  - scale.madrid.operator.com
  resources:
  - scaledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.madrid.operator.com
  resources:
  - scaledeployments/status
  verbs:
  - get
